#+TITLE: 定量研究方法课程作业1
#+AUTHOR: 厦门大学公共事务学院
#+EMAIL: 
#+OPTIONS: H:2 toc:nil num:t tex:t ^:nil
* 问题
第一部分：（来源：Gelman and Hill 2007 第2章课后习题，增加部分提示）
1. The following are the proportions of girl births in Vienna for each month in 1908 and 1909 (out of an average of 3900 births per month):
 
   .4777 .4875 .4859 .4754 .4874 .4864 .4813 .4787 .4895 .4797 .4876 .4859 .4857 .4907 .5010 .4903 .4860 .4911 .4871 .4725 .4822 .4870 .4823 .4973 

   von Mises (1957) used these proportions to claim that the sex ratios were less variable than would be expected by chance. 

   (a) Compute the standard deviation of these proportions and compare to the standard deviation that would be expected if the sexes of babies were independently decided with a constant probability over the 24-month period. 

   (b) The actual and theoretical standard deviations from (a) differ, of course. Is this difference statistically significant? (Hint: \((n-1)s^2 /\sigma^2 \sim \chi^2 (n-1) \)) 

2. Demonstration of the Central Limit Theorem: let x = x1 + · · · + x20, the sum of 20 independent Uniform(0,1) random variables. In R, create 1000 simulations of x and plot their histogram. On the histogram, overlay a graph of the normal density function. Comment on any differences between the histogram and the curve. 

   (Hint: the R function for getting 20 random values from uniform distribution with a starting point 0 and an ending point 1 is runif(20); you can use dnorm() to get a normal density function and use lines() to draw it)

3. Distribution of averages and differences: the heights of men in the United States are approximately normally distributed with mean 69.1 inches and standard deviation 2.9 inches. The heights of women are approximately normally distributed with mean 63.7 inches and standard deviation 2.7 inches. Let x be the average height of 100 randomly sampled men, and y be the average height of 100 randomly sampled women. In R, create 1000 simulations of x − y and plot their histogram. Using the simulations, compute the mean and standard deviation of the distribution of x − y and compare to their exact values. 

   (Hint: you can use rnorm(100, mean=69.1, sd=2.9) to get 100 simulated male random sample)

第二部分：
1. 在[[http://cgss.ruc.edu.cn/][中国综合社会调查网站]]上下载cgss2017的数据（spss版本）、问卷和编码表。
1. 在Rstudio中将数据导入，选择编号（id）、城乡（isurban）、居住省份（s41）、个人全年总收入（A8a）、出生年份（a31）、性别（A2）、教育程度（A7a）、政治面貌（A10）、工作年限（A59c）、工作经历及状态（A58）、父亲教育程度（A89b）、母亲教育程度（A90b）、父亲的工作单位类型（A89g）、母亲的工作单位类型（A90g）等变量构成新的工作数据集cgssincome2017，再根据城乡（isurban）变量选取城市的被调查对象（取值为1）并保存。
1. 新建一个项目，载入cgssincome2017数据集，将出生年份转化为年龄（2017年），教育程度（本人、父母）重新进行编码转化为教育年限，政治面貌重新进行编码转化为是否党员。并且设定所有的缺失值为NA（CGSS往年设定为-8是无法回答；-3拒绝回答；-2是不知道；-1是不适用，请自行确认2017年数据是否依然如此！），最后成行删除掉具有缺失值的观测（建议使用cgssincome <- na.omit(cgssincome)）。
注意：以上步骤如果采用菜单方式载入，haven包会默认给变量添加值标签，应采用zap_labels函数去除值标签，否则有些函数无法使用，如cgssincome <- zap_labels(cgssincome)
1. 将性别、是否党员转化为类别变量（因子factor函数），计算男女党员的交叉表; 制作收入的直方图(注意用参数breaks多分割一些区间)，收入是正态分布吗？如何让它变得更像正态分布？制作收入的箱线图，选取收入小于15万的观测再试试看；制作男女收入对比箱线图，收入存在性别差异吗？
1. 计算在置信水平为95%的条件下，居民收入的置信区间。
1. 假设有人提出2017年全国居民年平均收入为5万块，那么在0.05的显著性水平下，cgss的样本结果和这一提法一致吗？
1. 计算男性与女性的平均收入，在95%的置信水平下，收入是否存在性别差异？
1. 检验被调查者的父亲与母亲教育程度是否有差异？
* 第二部分数据 （第1-2步整理后数据，供参考，如无法独立完成第1-2步，可以载入后继续后面的分析）
[[./cgssincome2017.RData][cgssincome2017数据]]
* R代码 :noexport:
+ [[./homework1-part1.R][第一部分答案与代码]]
+ [[./homework-getdata2017.R][第二部分之数据导入与变量选取代码]]
+ [[./homework-analysis2017.R][第二部分之数据探索分析代码]]


